### ISSUE TITLE
`thc.ipynb` assertion fails occasionally

### ISSUE THREAD

**Issue by charlesyuan314** [quantumlib/Qualtran#1170]
This notebook has started to fail occasionally as of a few weeks ago.

Example log [here](https://github.com/quantumlib/Qualtran/actions/runs/10044825760/job/27760744975?pr=1169).

**Comment by mpharrigan** [comment]
Resource counting should definitely be deterministic. Are there any hypotheses on how this can flake?

 - some mysterious flaky decomposition, perhaps based on linear-algebra-based decomposition of something? maybe via a cirq routine that can flake due to numerical precision?
 - unseeded random sample data generation that can change the number of gates somehow?

**Comment by fdmalone** [comment]
Random number seeding is possible but I don't think the T counts should depend on the seed in a real way (unless there is some bitsize automatically being set based on the size of the elements (like qrom) and sometimes this leads to a smaller register.) I'll dig in.
