### ISSUE TITLE
TComplexity not working for several bloqs

### ISSUE THREAD

**Issue by mstechly** [quantumlib/Qualtran#1225]
While working on #1194 , I noticed that several bloqs throw the following exception:
```
E           TypeError: couldn't compute TComplexity of:
E           type: <class 'qualtran.bloqs.basic_gates.x_basis.MinusEffect'>
E           value: MinusEffect
```

Here's a list of these bloqs:

- `MinusState`
- `MinusEffect`
- `PlusEffect`
- `PlusState`
- `OneEffect`
- `OneState`
- `ZeroEffect`
- `ZeroState`
- `Product`
- `TopLeftRowColumnOracle`
- `C[TwoBitSwap]`
- `ModSub`
- `ECAddR`
- `ECWindowAddR`
- `MeasureQFT`

Not sure if that's an expected behaviour or not, perhaps throwing `NotImplementedError` or something even more specific would be more informative.

FYI apart from that I got a couple of other errors. They seem mostly associated with symbolics, such as: `ValueError: Split cannot have a symbolic data type.` or `TypeError: cirq.unitary failed. Value doesn't have a (non-parameterized) unitary effect.`.

**Comment by mpharrigan** [comment]
Thanks, tracking in https://github.com/quantumlib/Qualtran/pull/835#issuecomment-2259364268 as well. 

I'll treat this as a sub-bug of #735

**Comment by mpharrigan** [comment]
In the mean time, you should `except` these errors

**Comment by mpharrigan** [comment]
The new list is

```
scaled_chebyshev_poly_even DecomposeTypeError
product_block_encoding_symb DecomposeTypeError
ec_add DecomposeNotImplementedError
ec_add_r DecomposeNotImplementedError
ec_add_r_small DecomposeNotImplementedError
ec_window_add DecomposeNotImplementedError
ec_pe DecomposeNotImplementedError
ec_pe_small DecomposeNotImplementedError
ecc DecomposeNotImplementedError
```

Reminder:

 - `DecomposeNotImplementedError` means that we can't compute the cost because the bloq doesn't have a decomposition annotated and it isn't an atomic/leaf bloq. Bloqs aren't obligated to give their decomposition
 - `DecomposeTypeError` means you're trying to decompose something that ought not be decomposed: something with symbolic parameters or an atomic/leaf bloq that the gate counting code doesn't know what to do with. 

Other exception types would be a bug; but I think we've got all of those out now.
