### ISSUE TITLE
Half bloqs

### ISSUE THREAD

**Issue by NoureldinYosri** [quantumlib/Qualtran#1281]
Some bloqs have the same V shape (e.g. comparison) where a ladder of operations followed by a CNOT(some qubit, target qubit) then uncompute the ladder. 

For these bloqs being able to create half of it is benifical. For example the controlled version requires only one addition Toffoli since we need just to turn the CNOT into a Toffoli. Also having several of them in line which create a seesaw pattern (i.e. several Vs in line VVVVV) can be reduced to a single compute (FORWARD) and as single uncompute (BACKWARD) instances (i.e. `\` then `some work` then `/`)

I had a discussion of this some time ago with  @tanujkhattar  and we were thinking about passing some flag to the constructor to specify whether we want the full V shape or half of it. that's something like this

```py3
class BloqVersion(Enum):
    FULL = 0  # Full V shape
    FORWARD_WITHOUT_UPDATE = 1  # The first half of the decomposition without the CNOT 
    FORWARD_WITH_UPDATED = 2  # The first half of the decomposition with the CNOT
    BACKWARD = 3  # The second half of the decomposition
```

cc: @mpharrigan

**Comment by mpharrigan** [comment]
Why couldn't these just be separate bloqs?

**Comment by NoureldinYosri** [comment]
it is not that they can't ... it's an alternative ... this issue is about discussing this case and reaching a decision

**Comment by tanujkhattar** [comment]
I also think it'll be easier if they are just separate bloqs. Especially since the full bloq can call the half bloqs in its decomposition; the hierarchical structure makes it a natural choice. An example is `MultiAnd`; which is actually a half bloq and should probably be renamed to `AndLadder` since it computes a ladder of AND gates and gives you `n` ancillas as output. It can be used as a primitive when implementing `MultiControlX` that doesn't leave behind any ancillas. 

Such lower level bloqs that give you ancilla outputs; which can be composed to form bloqs that don't leave ancillas would be my preference. I believe this aligns with Matt's recommendation above.

**Comment by NoureldinYosri** [comment]
from the disucssion, the decision is to implement these cases as seprate bloqs
