### ISSUE TITLE
Signature of `_BookkeepingBloq.controlled()` does not match `Controlled(_BookkeepingBloq)`

### ISSUE THREAD

**Issue by anurudhp** [quantumlib/Qualtran#1326]
We currently return `self` for the controlled version of a bookkeeping bloq, which does not act on the ctrl registers. We should decide if this is okay, or if the signatures of `bloq.controlled()` and `Controlled(bloq)` should match. 
 
https://github.com/quantumlib/Qualtran/blob/84324f9ffe1ca79eb04a8360f62c356e20908caf/qualtran/bloqs/bookkeeping/_bookkeeping_bloq.py#L34-L44

**Comment by mpharrigan** [comment]
This is by design, and indeed why we need the `add_controlled` return value. If you're wiring up a controlled version of a bloq, you should use that method. We might want to add a `BloqBuilder.add_controlled(bloq)` helper method. 

The return value of `Bloq.controlled()` is very information-lossy. It doesn't tell you anything about where the new control registers can be

**Comment by mpharrigan** [comment]
I'm going to close based on your thumbs up, feel free to re-open with any additional questions or concerns
