### ISSUE TITLE
Resource estimation notebook for chemistry has (I think) a typo

### ISSUE THREAD

**Issue by wjhuggins** [quantumlib/Qualtran#1511]
In /bloqs/chemistry/resource_estimation.ipynb, the size of the data that needs to be loaded for the sparse simulation approach is given as O(N^3) but it should be O(N^4).

**Comment by fdmalone** [comment]
Asymptotically I think sparsity gains you 1/N saving assuming some
localization etc. Is that not the case? (Practically I imagine it may never
be seen)

**Comment by wjhuggins** [comment]
There is a line in the THC paper about how it might save a factor of N^2 in the asymptotic limit with localization but I think it would be good to either put N^4 or have more discussion about it in the notebook, or both.

**Comment by fdmalone** [comment]
I don't think sparsity could save a factor of N^2? If I remember things correctly worst case there would be O(N^4) elements so QROAM cost of O(N^2), with sparsity I thought best case it would save you a factor of N (for large N) so O(N^{1.5}) QROAM cost. Happy to change it to N^4 though since I imagine the this might only kick in for impractically large systems
