### ISSUE TITLE
Add a pylint check for line width < 100 characters

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/Qualtran#427]
@mpharrigan I don't think this exists yet?

**Comment by mpharrigan** [comment]
#101 

The formatter should handle this, no?

**Comment by vtomole** [comment]
As an aside, the Cirq check infrastructure is really good. It would be nice to place it on pypi as `cirq-check` or something so that libraries like this can import them and sidestep check discussions that [Cirq already solved](https://github.com/quantumlib/Cirq/issues/3292). Of course this is assuming that Qualtran wants to adopt Cirq's style, but this issue is an example that it wants to adopt most of it.

**Comment by mpharrigan** [comment]
Closing as duplicate and because I think this is low priority
