### ISSUE TITLE
TGate vs Toffoli as cost target

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#436]
Many papers give costs in terms of Toffoli gates which I've been converting to TGates by multiplying by four. Is this the way to go? Should I be leaving as Toffolis? Some gates (multi-controlled hadamards) have toffoli cost but aren't invertible at zero cost. Should we be capturing this somehow?

**Comment by mpharrigan** [comment]
In general, you should give the costs in as high-a-level as you know; and/or whatever is most natural. Here: you should leave as Toffoli instead of multiplying by four.

Can you speak more about the second statement? "aren't invertible at zero cost"? The toffoli gate will always cost 4 tgates whereas the `And(adjoint=True)` will require no magic states. I.e. we use a different bloq

**Comment by fdmalone** [comment]
For example, there are often statements like:

<img width="1158" alt="Screenshot 2023-10-25 at 9 39 56 AM" src="https://github.com/quantumlib/Qualtran/assets/12097876/d3418d1b-8a7c-43d4-a991-8e1d627372dd">

The controlled hadamards are related to #237. I was conflating Toffolis have zero inversion cost with "we gave these costs in terms of Toffolis but their inverse bloqs can be actually quite different so no Toffolis". So we really need to have adjoint decompositions for many of the arithmetic, comparators etc.

**Comment by mpharrigan** [comment]
Right; so do you think this will be solved by having specializations for the adjoint of operations?

**Comment by fdmalone** [comment]
Yes, thanks! I was confusing myself.
