### ISSUE TITLE
`PhaseGradientState` exponent should be float or int?

### ISSUE THREAD

**Issue by mpharrigan** [quantumlib/Qualtran#668]
`PhaseGradientState` annotates exponent as `int` and checks that in `__pow__`, but unit tests use floating point values.

**Comment by tanujkhattar** [comment]
It can be float. I'll send a fix.

However, this raises a good question - how do we handle `__pow__` for bloqs that have directional registers and also support arbitrary `exponent` ? For example, in this case should `phase_gradient_state ** -1` return an effect with LEFT register instead of a right register? What about `phase_gradient_state ** -0.5` ? 

I think in general, `bloq ** -1` and `bloq.adjoint` should be consistent. What do you think?
