### ISSUE TITLE
[data types] Shorten BoundedQUInt name

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/Qualtran#726]
It's a bit long (#724)

**Comment by anurudhp** [comment]
fwiw, in the PL community, I've seen "finite" used for this, e.g. Haskell's [`Finite`](https://hackage.haskell.org/package/finite-typelits-0.2.1.0/docs/Data-Finite.html), Lean's [`Fin`](https://leanprover-community.github.io/mathlib4_docs/Init/Prelude.html#Fin), as opposed to `Int`/`Nat` which are unbounded. But I guess in Qualtran all the types are finite/bounded, just that `BoundedQUInt` is _more_ bounded. So may be confusing to use finite.

**Comment by mpharrigan** [comment]
@fdmalone @anurudhp @tanujkhattar can you figure out this issue asap. Either come up with a name, alias; or close the issue as wont-fix.

"Finite" is kinda strange since all of our numbers are finite. You could make the same argument about "Bounded" since all our numbers are bounded by powers of two

**Comment by tanujkhattar** [comment]
I propose `BQUInt` as short of `BoundedQUInt`. We'll still keep the documentation to say `BoundedQUInt` but change the name to `BQUInt`. 

@fdmalone @anurudhp  Let me know what you think.

**Comment by fdmalone** [comment]
Can I just do this? Or will it cause merge hell.

**Comment by anurudhp** [comment]
BQUInt sounds good. @fdmalone I don't think it should cause any merge problems
